name: NucleusIOS
options:
  bundleIdPrefix: net.suherman
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
packages:
  NucleusCore:
    path: ../../Packages/NucleusCore
  NucleusUI:
    path: ../../Packages/NucleusUI
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  NucleusIOS:
    type: application
    platform: iOS
    sources:
      - path: NucleusIOS
        excludes:
          - entitlements.ios.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.suherman.nucleus
        INFOPLIST_FILE: NucleusIOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: NucleusIOS/entitlements.ios.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: Q3TXW887NM
        CURRENT_PROJECT_VERSION: 2
        MARKETING_VERSION: 1.0.0
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
    dependencies:
      - package: NucleusCore
        product: NucleusCore
      - package: NucleusUI
        product: NucleusUI
    scheme:
      testTargets:
        - NucleusIOSScreenshots

  NucleusIOSScreenshots:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: NucleusIOSScreenshots
    dependencies:
      - target: NucleusIOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.suherman.nucleus.screenshots
        DEVELOPMENT_TEAM: Q3TXW887NM
        GENERATE_INFOPLIST_FILE: YES

schemes:
  NucleusIOS:
    build:
      targets:
        NucleusIOS: all
    run:
      config: Debug
    test:
      targets:
        - NucleusIOSScreenshots
