#!/usr/bin/env node
/**
 * Build .env from .env.example, existing .env values, and GCP Secret Manager.
 * Also writes website/.env.local for Next.js local dev (Cloud Sync API).
 */
const fs = require("fs");
const path = require("path");
const { applyGcpEnv } = require("./apply-gcp-env.cjs");
const { parseEnvFile, resolveGcpProjectId } = require("./gcp-config.cjs");
const { resolveAdcPath } = require("./gcp-lib-adc.cjs");
const { MANAGED_SECRETS, accessSecret } = require("./gcp-secrets.cjs");

const repoRoot = path.join(__dirname, "..");
const examplePath = path.join(repoRoot, ".env.example");
const envPath = path.join(repoRoot, ".env");
const websiteEnvPath = path.join(repoRoot, "website", ".env.local");

const WEBSITE_ENV_KEYS = [
  "GCP_PROJECT_ID",
  "GOOGLE_APPLICATION_CREDENTIALS",
  "AUTH_SECRET",
  "GOOGLE_OAUTH_CLIENT_ID",
  "GOOGLE_OAUTH_CLIENT_SECRET",
  "GOOGLE_OAUTH_REDIRECT_URI",
  "WEBSITE_BASE_URL",
  "NEXT_PUBLIC_REGISTRY_API_URL",
  "NEXT_PUBLIC_APP_ID",
  "NEXT_PUBLIC_DOWNLOAD_BASE_URL",
];

function fail(message) {
  console.error(`generate-env: ${message}`);
  process.exit(1);
}

function orderedKeys(exampleContent, existingKeys, secretKeys) {
  const keys = [];
  const seen = new Set();

  for (const line of exampleContent.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    if (!seen.has(key)) {
      seen.add(key);
      keys.push(key);
    }
  }

  for (const key of existingKeys) {
    if (!seen.has(key)) {
      seen.add(key);
      keys.push(key);
    }
  }

  for (const key of secretKeys) {
    if (!seen.has(key)) {
      seen.add(key);
      keys.push(key);
    }
  }

  return keys;
}

function formatEnv(keys, values) {
  const lines = [];
  for (const key of keys) {
    const value = values[key];
    if (value === undefined || value === "" || value === "undefined") continue;
    lines.push(`${key}=${value}`);
  }
  return `${lines.join("\n")}\n`;
}

function writeWebsiteEnvLocal(merged) {
  const localWebsiteUrl = merged.LOCAL_WEBSITE_URL?.trim() || "http://127.0.0.1:3000";
  const websiteValues = {
    ...merged,
    WEBSITE_BASE_URL: localWebsiteUrl,
    GOOGLE_OAUTH_REDIRECT_URI: `${localWebsiteUrl}/api/auth/google/callback`,
    NEXT_PUBLIC_REGISTRY_API_URL:
      merged.NEXT_PUBLIC_REGISTRY_API_URL?.trim() || "http://127.0.0.1:8080",
    NEXT_PUBLIC_DOWNLOAD_BASE_URL:
      merged.LOCAL_DOWNLOAD_BASE_URL?.trim() || `${localWebsiteUrl}/downloads`,
  };

  const lines = [
    "# Generated by npm run generate-env — do not commit",
    ...WEBSITE_ENV_KEYS.filter((key) => websiteValues[key] && websiteValues[key] !== "undefined").map(
      (key) => `${key}=${websiteValues[key]}`,
    ),
  ];

  fs.writeFileSync(websiteEnvPath, `${lines.join("\n")}\n`, "utf8");
  console.log(`generate-env: wrote ${websiteEnvPath}`);
}

function main() {
  if (!fs.existsSync(examplePath)) {
    fail("missing .env.example");
  }

  applyGcpEnv(repoRoot);

  const exampleContent = fs.readFileSync(examplePath, "utf8");
  const example = parseEnvFile(examplePath);
  const existing = parseEnvFile(envPath);
  const projectId = resolveGcpProjectId(repoRoot);

  if (!projectId) {
    fail("GCP_PROJECT_ID is not set. Add it to .env or run npm run login.");
  }

  const secrets = {};
  for (const key of MANAGED_SECRETS) {
    try {
      secrets[key] = accessSecret(projectId, key);
      console.log(`generate-env: loaded ${key} from Secret Manager`);
    } catch (error) {
      if (existing[key] && existing[key] !== "undefined") {
        secrets[key] = existing[key];
        console.log(`generate-env: kept local ${key} (Secret Manager unavailable)`);
        continue;
      }
      console.log(`generate-env: skip ${key} (${error.message})`);
    }
  }

  const merged = { ...example, ...existing, ...secrets };
  const adcPath = resolveAdcPath(repoRoot, { sync: true });
  if (adcPath) {
    merged.GOOGLE_APPLICATION_CREDENTIALS = adcPath;
  } else {
    delete merged.GOOGLE_APPLICATION_CREDENTIALS;
    console.log(
      "generate-env: no ADC file found — run gcloud auth application-default login, then npm run generate-env",
    );
  }

  const keys = orderedKeys(exampleContent, Object.keys(existing), MANAGED_SECRETS);
  fs.writeFileSync(envPath, formatEnv(keys, merged), "utf8");
  console.log(`generate-env: wrote ${envPath}`);

  writeWebsiteEnvLocal(merged);
}

main();
